---
kind: pipeline
name: default

steps:
- name: build
  image: golang:1.20.0
  volumes:
  - name: deps
    path: /go
  commands:
  - make

- name: test
  image: golang:1.20.0
  volumes:
  - name: deps
    path: /go
  commands:
  - make test

- name: linter
  image: golang:1.20.0
  volumes:
  - name: deps
    path: /go
  commands:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s
    - ./bin/golangci-lint run

- name: telegram
  image: appleboy/drone-telegram
  settings:
    to: 790376882
    format: markdown
    token:
      from_secret: telegram_token

volumes:
- name: deps
  host:
    path: /var/lib/cache/godeps/
